name: 'Main: Download rules from external sources'

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting-up GitHub username
        run: |
          git config --global user.email "github@actions"
          git config --global user.name "Repository manager"
          
      - name: Listing files
        run: ls -la
